CONFIG	=/usr/X11R6/lib/X11/config
PROJECT	=/usr/local/src/OZ++-R5

RELEASE	= 5
SHELL	= /bin/sh
RM	= rm -f
MV	= mv

FLAGS	= $(MFLAGS) -DUseInstalled -I$(CONFIG) \
		-DProject=$(PROJECT) -DRelease=$(RELEASE)

all::
	@echo ""
	@echo "Please, make World"
	@echo ""

World::
	@echo ""
	@echo "OZ++ System Release $(RELEASE): Build"
	@date
	@echo ""

World:: Makefile
	@make Makefiles clean include depend all

tar::	Makefile
	@make Makefiles tar

Makefile::
	@if [ -f Makefile -o -h Makefile ]; then \
	   $(RM) Makefile.bak ; $(MV) Makefile Makefile.bak ;\
	 fi
	imake $(FLAGS)
